name: '🏗 deploy_dev → rundgang-frontend-24.dev.medienhaus.udk-berlin.de'

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA to checkout
        required: true
        default: 'main'

jobs:
  deploy_dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.inputs.ref}}

      - name: Sync files to remote host
        uses: up9cloud/action-rsync@v1.1
        env:
          HOST: dev.medienhaus.udk-berlin.de
          KEY: ${{secrets.SSH_DEV_MEDIENHAUS_UDK_BERLIN_DE}}
          TARGET: /opt/rundgang-frontend-24/
          VERBOSE: true
          USER: root
          PORT: 22
          ARGS: --recursive --update --delete --compress --exclude=/.git/ --exclude=/public/fonts/
          SSH_ARGS: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          SOURCE: .

      - name: Restart rundgang-frontend-24 service
        uses: fifsky/ssh-action@v0.0.5
        with:
          command: |
            cd /opt/rundgang-frontend-24/
            npm clean-install
            npm run build
            systemctl restart rundgang-frontend-24.service
          host: dev.medienhaus.udk-berlin.de
          user: root
          key: ${{secrets.SSH_DEV_MEDIENHAUS_UDK_BERLIN_DE}}
